### ISSUE TITLE
update  X11/Graphics/X11/ExtraTypes/XF86.hsc

### ISSUE THREAD

**Issue by vrs** [xmonad/X11#36] opened 2015-12-10 12:39 UTC
The last change to this file was in 2008. I don't know when XF86XK_Battery was added but my /usr/include/X11/XF86keysym.h has it (it is used on some thinkpads for example). Time for an update?

**Comment by dmwit** [comment] 2015-12-13 01:13
This looks like a duplicate of issue #21 to me.

**Closed by dmwit** 2015-12-13 01:13 UTC
